version: '3.4'
services:
  nginx:
    image: nginx:alpine
    working_dir: /application
    networks:
      default:
        aliases:
          - mock
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${APP_PORT}:80
    links:
      - php-fpm
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      target: dev
      dockerfile: docker/Dockerfile
    working_dir: /application
    volumes:
      - .:/application
      - composer:/tmp/composer
    environment:
      PHP_IDE_CONFIG: "serverName=sap-integration.localhost"
      COMPOSER_HOME: "/tmp/composer"
    extra_hosts:
      - host.docker.internal:host-gateway

  zookeeper:
    restart: on-failure
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2182:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    restart: on-failure
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9092'
      - '9095:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=CLIENT://:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

volumes:
  dbdata:
    driver: local
  composer:
    driver: local
